spring.application.name=servease

spring.datasource.url=jdbc:mysql://localhost:3306/servease
spring.datasource.username=root
spring.datasource.password=Nirmal@2005

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update